version: "3.9"

services:
  gateway:
    build: .
    container_name: 'gws-gateway'
    ports:
      - '1000:1000'

  consul:
    image: bitnami/consul
    container_name: "gws-consul"
    ports:
      - "8500:8500"
    command: "consul agent -dev -ui -client=0.0.0.0"

networks:
  default:
    name: gws-net
    driver: bridge
