server:
  port: 1000
  error:
    include-message: always
    include-binding-errors: always

oauth:
  google:
    clientId: "1080328209799-na3qao6s6art0rgolnfn3q5ceo63akc3.apps.googleusercontent.com"
    clientSecret: "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"
    scope: "openid profile email"

spring:
  application:
    name: gateway
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        enabled: false
    gateway:
      routes:
        - id: hw2
          uri: https://profitsofthw2-spne32jrqq-lm.a.run.app
          predicates:
            - Path=/api/book/**,/api/author/**
        - id: gateway
          uri: lb://gateway
          predicates:
            - Path=/oauth/**
        - id: frontend
          uri: https://master.dgu7m57sa2t9p.amplifyapp.com/
          predicates:
            - Path=/**

  datasource:
    url: jdbc:postgresql://dpg-cpunm8aj1k6c738e7fmg-a.frankfurt-postgres.render.com/db_8c8t
    username: user
    password: 8p4EpesaV3FD8935N9EbKcMIW0DLRhk3
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

resilience4j:
  circuitbreaker:
    instances:
      services:
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        slow-call-duration-threshold:
          - 2s
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"